name: Deploy library

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release-package:
    runs-on: ubuntu-20.04
    name: Release package
    permissions:
      contents: write
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Release Python package
        uses: hsorby/release-python-package-action@main
        with:
          release-repository: hsorby/cmlibs.maths
          pypi-package-name: cmlibs.maths
          github-token: ${{ secrets.GITHUB_TOKEN }}
