name: Deploy library

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release-package:
    if: github.repository == 'hsorby/cmlibs.maths'
    runs-on: ubuntu-20.04
    name: Release package
    permissions:
      contents: write
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Release Python package
        uses: hsorby/release-python-package-action@main
        with:
          pypi-package-name: cmlibs.maths
